### ISSUE TITLE
Add Support for FIPS Compliance

### ISSUE THREAD

**Issue by aghassemlouei** [aws/crypto-tools#29]
For at least aws-crypto version 3.0.0 and above Federal Information Processing Standard (FIPS) 140-2 and/or 140-3 support is needed to comply with United States requirements. Including some additional information related to FIPS for any individuals unfamiliar with it:

* https://en.wikipedia.org/wiki/Federal_Information_Processing_Standards
* https://en.wikipedia.org/wiki/FIPS_140-2
* https://en.wikipedia.org/wiki/FIPS_140-3

We have also opened AWS support case 171388344200140 to improve visibility.

**Comment by kessplas** [comment]
Hi there,
 
The tools that we produce (Encryption SDK, S3 Encryption Client, Database Encryption SDK, etc) use cryptographic primitive providers such as OpenSSL, AWS-LC or BouncyCastle to perform cryptographic operations.  Our position is that you should combine your use of Encryption SDK with a FIPS compliant cryptographic primitive provider (AWS-LC for example).  Please reach out to your TAM and we can walk you through your specific use-case.
